# Generated by Django 3.0.5 on 2020-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablatures', '0003_auto_20200411_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tablature_source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
