# Generated by Django 3.0.5 on 2020-04-24 20:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tablatures', '0004_auto_20200411_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tuning',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(12, 'C1'), (24, 'C2'), (36, 'C3'), (48, 'C4'), (60, 'C5'), (13, 'C#1'), (25, 'C#2'), (37, 'C#3'), (49, 'C#4'), (61, 'C#5'), (14, 'D1'), (26, 'D2'), (38, 'D3'), (50, 'D4'), (62, 'D5'), (15, 'D#1'), (27, 'D#2'), (39, 'D#3'), (51, 'D#4'), (63, 'D#5'), (16, 'E1'), (28, 'E2'), (40, 'E3'), (52, 'E4'), (64, 'E5'), (17, 'F1'), (29, 'F2'), (41, 'F3'), (53, 'F4'), (65, 'F5'), (18, 'F#1'), (30, 'F#2'), (42, 'F#3'), (54, 'F#4'), (66, 'F#5'), (19, 'G1'), (31, 'G2'), (43, 'G3'), (55, 'G4'), (67, 'G5'), (20, 'G#1'), (32, 'G#2'), (44, 'G#3'), (56, 'G#4'), (68, 'G#5'), (21, 'A1'), (33, 'A2'), (45, 'A3'), (57, 'A4'), (69, 'A5'), (22, 'A#1'), (34, 'A#2'), (46, 'A#3'), (58, 'A#4'), (70, 'A#5'), (23, 'B1'), (35, 'B2'), (47, 'B3'), (59, 'B4'), (71, 'B5')], default='', max_length=179),
            preserve_default=False,
        ),
    ]
