# Generated by Django 3.0.5 on 2020-07-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablatures', '0006_auto_20200503_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='tuning',
        ),
    ]
